### PR TITLE
Update README, Travis and dependencies

### LINKED ISSUE #1: Action required: Greenkeeper could not be activated 🚨
🚨 You need to enable Continuous Integration on Greenkeeper branches of this repository. 🚨

To enable Greenkeeper, you need to make sure that a [commit status](https://help.github.com/articles/about-statuses/) is reported on all branches. This is required by Greenkeeper because it uses your CI build statuses to figure out when to notify you about breaking changes.

Since we didn’t receive a CI status on the [`greenkeeper/initial`](https://github.com/watson-developer-cloud/assistant-demo/commits/greenkeeper/initial) branch, it’s possible that you don’t have CI set up yet. We recommend using [Travis CI](https://travis-ci.org), but Greenkeeper will work with every other CI service as well.

If you _have_ already set up a CI for this repository, you might need to check how it’s configured. Make sure it is set to run on all new branches. If you don’t want it to run on absolutely every branch, you can whitelist branches starting with `greenkeeper/`.

Once you have installed and configured CI on this repository correctly, you’ll need to re-trigger Greenkeeper’s initial pull request. To do this, please click the 'fix repo' button on [account.greenkeeper.io](https://account.greenkeeper.io).

### PR DESCRIPTION
**Pull request by germanattanasio**
Fixes #1 and #3

### CODE REVIEW

**Comment by repjarms** [comment]
@germanattanasio why did we remove `CleanWebpackPlugin` in this PR?

That plugin removes any existing `dist` folder before rebundling a new one. It is very helpful in ensuring that artifacts that may be left over between bundling (especially as public folders, etc change) don't get left behind.

I don't see any reason to remove it.

**Comment by germanattanasio** [comment]
When you run the dev version it removes the `dist` folder so everytime you run the dev version and after that you want to run the tests they fail because there is no `dist` folder so you have to remember to do `npm run build` everytime you have to run the tests even if the changes are in the backend

**Comment by repjarms** [comment]
That's a fair point @germanattanasio , but in that case I think the correct approach is to move the `CleanWebpackPlugin` to the `webpack.prod.config.js` file, so that the dist folder is cleaned implicitly when someone runs `npm run build`. I think removing it completely will lead to some pretty opaque problems down the line with build artifacts getting left over (especially since in Travis we aren't clearing cache).

The issues you brought up about the plugin running in dev mode are definitely true, not to mention that it slows down test execution time due to having to clear and rebuild every time when someone is working locally.

Can we add the plugin back in within our production configuration?

**Comment by germanattanasio** [comment]
@repjarms That's a good idea!

I added `CleanWebpackPlugin` back but only for the prod config

**Comment by Oliver-I** [comment]
@germanattanasio It looks like you've removed the demo link. Please add that back to the readme file to make it consistent with the other sample apps - it's not apparent that clicking on the gif will open the demo.

image

Also, as discussed, we're not accepting contributions for this sample app, we should remove the Contributions section in the readme to help avoid confusion.

**Pull request merged**
